import type { INodeProperties } from 'n8n-workflow';

const showOnlyForSystem = {
	resource: ['system'],
};

export const systemProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showOnlyForSystem },
		options: [
			{
				name: 'App Change',
				value: 'appchange',
				description: 'Change software applications for an account (experimental)',
				action: 'App change',
			},
			{
				name: 'Backup',
				value: 'backup',
				description: 'Create a complete account backup',
				action: 'Backup',
			},
			{
				name: 'Batch',
				value: 'batch',
				description: 'Run a method on one or more accounts',
				action: 'Batch',
			},
			{
				name: 'Check',
				value: 'check',
				description: 'Check accounts for outages and restart if needed',
				action: 'Check',
			},
			{
				name: 'Database',
				value: 'database',
				description: 'Import or export account database',
				action: 'Database',
			},
			{
				name: 'Info',
				value: 'info',
				description: 'Get state (up/down) of accounts',
				action: 'Info',
			},
			{
				name: 'List Accounts',
				value: 'listaccounts',
				description: 'List all accounts',
				action: 'List accounts',
			},
			{
				name: 'List Hosts',
				value: 'listhosts',
				description: 'List all hosting servers',
				action: 'List hosts',
			},
			{
				name: 'List Regions',
				value: 'listregions',
				description: 'List all regions',
				action: 'List regions',
			},
			{
				name: 'Process Logs',
				value: 'processlogs',
				description: 'Process and rotate log files',
				action: 'Process logs',
			},
			{
				name: 'Provision',
				value: 'provision',
				description: 'Create a new streaming server account',
				action: 'Provision',
			},
			{
				name: 'Rename',
				value: 'rename',
				description: 'Change account username',
				action: 'Rename',
			},
			{
				name: 'Reparent',
				value: 'reparent',
				description: 'Move account to another reseller',
				action: 'Reparent',
			},
			{
				name: 'Restore',
				value: 'restore',
				description: 'Restore an account backup',
				action: 'Restore',
			},
			{
				name: 'Sanity Check',
				value: 'sanitycheck',
				description: 'Test communication with Centova Cast',
				action: 'Sanity check',
			},
			{
				name: 'Set Status',
				value: 'setstatus',
				description: 'Enable or disable an account',
				action: 'Set status',
			},
			{
				name: 'Terminate',
				value: 'terminate',
				description: 'Permanently remove an account',
				action: 'Terminate',
			},
			{
				name: 'Usage',
				value: 'usage',
				description: 'Get resource utilization of accounts',
				action: 'Usage',
			},
			{
				name: 'Version',
				value: 'version',
				description: 'Get Centova Cast version info',
				action: 'Version',
			},
		],
		default: 'listaccounts',
	},

	// System operations that need a username
	{
		displayName: 'Account Username',
		name: 'systemUsername',
		type: 'string',
		default: '',
		required: true,
		description: 'The account username to operate on',
		displayOptions: {
			show: {
				resource: ['system'],
				operation: [
					'rename',
					'setstatus',
					'check',
					'info',
					'usage',
					'appchange',
					'terminate',
					'reparent',
				],
			},
		},
	},

	// rename
	{
		displayName: 'New Username',
		name: 'newusername',
		type: 'string',
		default: '',
		required: true,
		description: 'The new username for the account',
		displayOptions: { show: { resource: ['system'], operation: ['rename'] } },
	},

	// setstatus
	{
		displayName: 'Status',
		name: 'accountStatus',
		type: 'options',
		options: [
			{ name: 'Enabled', value: 'enabled' },
			{ name: 'Disabled', value: 'disabled' },
		],
		default: 'enabled',
		required: true,
		description: 'Account status to set',
		displayOptions: { show: { resource: ['system'], operation: ['setstatus'] } },
	},

	// reparent
	{
		displayName: 'New Reseller',
		name: 'newreseller',
		type: 'string',
		default: '',
		required: true,
		description: 'Destination reseller username or "admin"',
		displayOptions: { show: { resource: ['system'], operation: ['reparent'] } },
	},

	// terminate
	{
		displayName: 'Client Action',
		name: 'clientaction',
		type: 'options',
		options: [
			{ name: 'Delete', value: 'delete' },
			{ name: 'Reparent', value: 'reparent' },
		],
		default: 'delete',
		description: 'What to do with sub-accounts when removing a reseller',
		displayOptions: { show: { resource: ['system'], operation: ['terminate'] } },
	},
	{
		displayName: 'Target Reseller',
		name: 'targetreseller',
		type: 'string',
		default: '',
		description: 'Destination reseller for reparenting',
		displayOptions: {
			show: { resource: ['system'], operation: ['terminate'], clientaction: ['reparent'] },
		},
	},

	// batch
	{
		displayName: 'Method',
		name: 'batchMethod',
		type: 'string',
		default: '',
		required: true,
		description: 'ServerControl method name to run (e.g. "start", "stop", "restart")',
		displayOptions: { show: { resource: ['system'], operation: ['batch'] } },
	},
	{
		displayName: 'Usernames',
		name: 'batchUsernames',
		type: 'string',
		default: '',
		required: true,
		description: 'Comma-separated usernames or "all"',
		displayOptions: { show: { resource: ['system'], operation: ['batch'] } },
	},

	// listaccounts
	{
		displayName: 'Additional Fields',
		name: 'listOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['system'], operation: ['listaccounts'] } },
		options: [
			{
				displayName: 'Start',
				name: 'start',
				type: 'number',
				default: 0,
				description: 'First account offset',
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				description: 'Maximum accounts to return',
			},
			{
				displayName: 'Filter',
				name: 'filter',
				type: 'string',
				default: '',
				description: 'Keyword filter',
			},
		],
	},

	// provision
	{
		displayName: 'Username',
		name: 'provisionUsername',
		type: 'string',
		default: '',
		required: true,
		description: 'Account username to create',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Hostname',
		name: 'provisionHostname',
		type: 'string',
		default: '',
		required: true,
		description: 'Stream hostname',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'IP Address',
		name: 'provisionIp',
		type: 'string',
		default: '',
		required: true,
		description: 'Listening IP address',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Port',
		name: 'provisionPort',
		type: 'string',
		default: 'auto',
		required: true,
		description: 'Listening port or "auto"',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'RPC Host ID',
		name: 'rpchostid',
		type: 'number',
		default: 1,
		required: true,
		description: 'Hosting server ID',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Max Clients',
		name: 'provisionMaxClients',
		type: 'number',
		default: 100,
		required: true,
		description: 'Maximum simultaneous listeners',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Admin Password',
		name: 'provisionAdminPassword',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		required: true,
		description: 'Account password',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Source Password',
		name: 'provisionSourcePassword',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		required: true,
		description: 'Source connection password',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Max Bitrate (kbps)',
		name: 'provisionMaxBitrate',
		type: 'number',
		default: 128,
		required: true,
		description: 'Maximum bitrate in kbps',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Transfer Limit (MB)',
		name: 'provisionTransferLimit',
		type: 'string',
		default: 'unlimited',
		required: true,
		description: 'Monthly data transfer in MB or "unlimited"',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Disk Quota (MB)',
		name: 'provisionDiskQuota',
		type: 'string',
		default: 'unlimited',
		required: true,
		description: 'Disk space in MB or "unlimited"',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Title',
		name: 'provisionTitle',
		type: 'string',
		default: '',
		required: true,
		description: 'Stream title',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Organization',
		name: 'provisionOrg',
		type: 'string',
		default: '',
		required: true,
		description: 'Company or organization name',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Email',
		name: 'provisionEmail',
		type: 'string',
		default: '',
		required: true,
		description: 'Account email address',
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'provisionOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['system'], operation: ['provision'] } },
		options: [
			{ displayName: 'Genre', name: 'genre', type: 'string', default: '' },
			{
				displayName: 'URL',
				name: 'url',
				type: 'string',
				default: '',
				description: 'Associated website URL',
			},
			{
				displayName: 'Auto Start',
				name: 'autostart',
				type: 'boolean',
				default: false,
				description: 'Whether to auto-start the stream',
			},
			{
				displayName: 'Server Type',
				name: 'servertype',
				type: 'string',
				default: '',
			},
			{
				displayName: 'App Types',
				name: 'apptypes',
				type: 'string',
				default: '',
				description: 'Supporting application types',
			},
			{
				displayName: 'Template',
				name: 'template',
				type: 'string',
				default: '',
				description: 'Account template name',
			},
			{ displayName: 'Charset', name: 'charset', type: 'string', default: '' },
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: '',
				description: 'UTC offset or "auto"',
			},
			{
				displayName: 'Allow Proxy',
				name: 'allowproxy',
				type: 'boolean',
				default: false,
				description: 'Whether to allow port-80 proxy access',
			},
			{
				displayName: 'Locale',
				name: 'locale',
				type: 'string',
				default: '',
				description: 'Language locale',
			},
			{
				displayName: 'Use Source',
				name: 'usesource',
				type: 'options',
				options: [
					{ name: 'Disabled (0)', value: 0 },
					{ name: 'Enabled (1)', value: 1 },
					{ name: 'On Demand (2)', value: 2 },
				],
				default: 0,
				description: 'AutoDJ usage mode',
			},
		],
	},

	// appchange
	{
		displayName: 'New App',
		name: 'newapp',
		type: 'string',
		default: '',
		required: true,
		description: 'New application identifier',
		displayOptions: { show: { resource: ['system'], operation: ['appchange'] } },
	},

	// backup
	{
		displayName: 'Backup Scope',
		name: 'backupScope',
		type: 'options',
		options: [
			{ name: 'All Accounts', value: 'all' },
			{ name: 'User Accounts Only', value: 'users' },
			{ name: 'Reseller Accounts Only', value: 'resellers' },
			{ name: 'Single Account', value: 'single' },
		],
		default: 'single',
		required: true,
		description: 'Which accounts to back up',
		displayOptions: { show: { resource: ['system'], operation: ['backup'] } },
	},
	{
		displayName: 'Account Username',
		name: 'backupUsername',
		type: 'string',
		default: '',
		required: true,
		description: 'Username of account to back up',
		displayOptions: {
			show: { resource: ['system'], operation: ['backup'], backupScope: ['single'] },
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'backupOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['system'], operation: ['backup'] } },
		options: [
			{
				displayName: 'Skip Media Files',
				name: 'nocontent',
				type: 'boolean',
				default: false,
				description: 'Whether to skip media files',
			},
			{
				displayName: 'Skip Log Files',
				name: 'nologs',
				type: 'boolean',
				default: false,
				description: 'Whether to skip log files',
			},
		],
	},

	// restore
	{
		displayName: 'Username',
		name: 'restoreUsername',
		type: 'string',
		default: '',
		required: true,
		description: 'Username for the restored account',
		displayOptions: { show: { resource: ['system'], operation: ['restore'] } },
	},
	{
		displayName: 'Filename',
		name: 'restoreFilename',
		type: 'string',
		default: '',
		required: true,
		description: 'Backup file path on server',
		displayOptions: { show: { resource: ['system'], operation: ['restore'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'restoreOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['system'], operation: ['restore'] } },
		options: [
			{
				displayName: 'RPC Host ID',
				name: 'rpchostid',
				type: 'number',
				default: 0,
				description: 'Destination hosting server ID',
			},
			{
				displayName: 'Reseller',
				name: 'reseller',
				type: 'string',
				default: '',
				description: 'Destination reseller username',
			},
			{
				displayName: 'Dry Run',
				name: 'dryrun',
				type: 'boolean',
				default: false,
				description: 'Whether to test without actually restoring',
			},
			{
				displayName: 'Overwrite',
				name: 'overwrite',
				type: 'boolean',
				default: false,
				description: 'Whether to overwrite an existing account',
			},
		],
	},

	// database
	{
		displayName: 'Database Action',
		name: 'dbAction',
		type: 'options',
		options: [
			{ name: 'Import', value: 'import' },
			{ name: 'Export', value: 'export' },
		],
		default: 'export',
		required: true,
		description: 'Import or export a database backup',
		displayOptions: { show: { resource: ['system'], operation: ['database'] } },
	},
	{
		displayName: 'Database Username',
		name: 'dbUsername',
		type: 'string',
		default: '',
		required: true,
		description: 'Account username for database operation',
		displayOptions: { show: { resource: ['system'], operation: ['database'] } },
	},
	{
		displayName: 'Filename',
		name: 'dbFilename',
		type: 'string',
		default: '',
		required: true,
		description: 'Import/export file path on server',
		displayOptions: { show: { resource: ['system'], operation: ['database'] } },
	},
];
